# Generated by Django 5.0.3 on 2024-03-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0025_rename_uploaded_file_uploadwork_uploded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadwork',
            name='uploded_file',
            field=models.FileField(upload_to='uploadwork/'),
        ),
    ]
